### PR TITLE
fixed test_emf.py to match some recent changes

### PR DESCRIPTION
**Pull request by JohnCremona**

### CODE REVIEW

**Comment by JohnCremona** [comment]
Update to this about to arrive...

**Comment by JohnCremona** [comment]
OK, now there are no failures or errors in running test.sh !  Please merge.

**Comment by fredstro** [comment]
All tests except the test_Llcalcurl passes which sporadically fails but this test should be removed...

**Comment by JohnCremona** [comment]
On 16 December 2015 at 13:06, Fredrik Strömberg <notifications@github.com>
wrote:

> All tests except the test_Llcalcurl passes which sporadically fails but
> this test should be removed...
>

Ok, I am removing it...

John

**Pull request merged**
