### PR TITLE
Improve setting of extended properties.

### PR DESCRIPTION
**Pull request by sehlen**

### CODE REVIEW

**Comment by JohnCremona** [comment]
Stephan, just checking that you did want this PR to be to Fredrik's refactor and not mine?  Since you left we have used mine as the merging point.  it's also fine of you and Fredrik work this wasy as before as long as Fredrik remembers to issue a pull request from his refactor branch to mine, at regular intervals.

**Comment by sehlen** [comment]
Well, this was in fact before we left.
One of us can issue a pull request to your refactor branch soon that will include this code.

**Comment by JohnCremona** [comment]
OK sorry, I was confused at first yesterday (e.g. one of my own branches got merged to my own master instead of my own refactor, so I then could not work out where the changes had disappeared to.  Now resolved.)

**Comment by JohnCremona** [comment]
Can you make a pull request to my refactor branch?  I checked that it will
merge without problems;  there are some (presumaly trivial) test failures
in test_emf.py  but I can fix those.

**Comment by fredstro** [comment]
Ok. I will do that

**Comment by JohnCremona** [comment]
In fact not all test failures are trivial!

ModularForm/GL2/Q/holomorphic/11/2/1/

fails after merging -- is this a data problem?

**Comment by fredstro** [comment]
this was a problem with the versioning system which I made more strict since I want to recompute the data and make sure that all new records are correct. 
The problem was that I simply updated the version (from 1.3 to 1.4) but then added version as a unique key.. I now run a script to change back to 1.3...

**Pull request merged**
